### ISSUE TITLE
provide an option to use cute_coroutine.h in cute_headers

### ISSUE THREAD

**Issue by liigo** [RandyGaul/cute_framework#25]
cute_framework depends on minicoro now, instead of [cute_coroutine.h](https://github.com/RandyGaul/cute_headers/blob/master/cute_coroutine.h) in cute_headers.

**Comment by RandyGaul** [comment]
Hi there! I just turned on notifications for this repo -- sorry for missing this earlier.

Do you dislike minicoro?

By the way, it is completely possible to simply download and use cute_coroutine.h yourself rather than minicoro, if you don't like CF's coroutine API. I'm just curious to hear more on what your idea is about.

**Comment by liigo** [comment]
Thank you for the response!

minicoro is not a pure c library, it has many assembly code, so has its portability flaw. i can not cross compile it for an iMX6UL based Linux device (x86), for example.

P.S. I'm not request dismissing minicoro though, just want another optional replacement.

By the way, I would like to ask, why you prefer minicoro to cute_coroutine.h (of yourself) ?

**Comment by RandyGaul** [comment]
I would like to work with the minicoro author and try to get portability pretty good, so thanks for mentioning the problem. Did you see problems with any other platform or just that one?

the problem with cute coroutine is it’s macro based, so local variables are not persisted in a simple way, and there are some limitations regarding order of macros and their internal scopes. With minicoro you can write plain C code, making it very difficult to break or use improperly.

**Comment by edubart** [comment]
> minicoro is not a pure c library, it has many assembly code, so has its portability flaw.

Minicoro uses just C code, but the code is not strict C standard, because it relies on assembly extensions from GCC for the assembly backend on Unix systems, supported since GCC 3.0 by either GCC or Clang. But the assembly can be disabled if you force the fallback `ucontext` backend by defining the macro `MCO_USE_UCONTEXT`, although `ucontext` is slower an may not be supported in some exotic operation systems. However this should usually be done by automatically when the library detects that assembly extension is not available.

>  i can not cross compile it for an iMX6UL based Linux device (x86), for example.

I've looked up and iMX6UL looks like to be an ARM based device, not x86, based on ARM Cortex A7/A9 according to Wikipedia, and my tests for minicoro on Cortex A7/A9 compiles and pass. But I'm testing using GCC 7.5 toolchain for ARM and QEMU to emulate the device, specifically the ARM [toolchain from Linaro](http://releases.linaro.org/components/toolchain/binaries/7.5-2019.12/), maybe you upgrade your toolchain if possible.

> P.S. I'm not request dismissing minicoro though, just want another optional replacement.

If you could provide additional details on what failed there, then perhaps the minicoro library could be improved in the future, or at least we could clarify on what scenarios it may not work. Like Randy mentioned, minicoro tries to have a good portability, specially the mainstream platforms and architectures.

**Comment by liigo** [comment]
> I've looked up and iMX6UL looks like to be an ARM based device, not x86, based on ARM Cortex A7/A9 according to Wikipedia

yes, you are right, my wrong.

> But I'm testing using GCC 7.5 toolchain for ARM ... If you could provide additional details on what failed there ...

My device's official sdk/toolchain using a pretty old gcc (4.6.2). Would you still like need some error details for that? I'm having a GCC 10.1 toolchain for testing, will try again. Thank you.

**Comment by liigo** [comment]
iMX6UL, Linux, GCC 10.2 toolchain, minicoro, they work well. 

```
root@freescale /mnt/nfs$ ./simple
coroutine 1
coroutine 2
root@freescale /mnt/nfs$ ./example 
fib 1 = 1
fib 2 = 1
fib 3 = 2
fib 4 = 3
fib 5 = 5
fib 6 = 8
fib 7 = 13
fib 8 = 21
fib 9 = 34
fib 10 = 55
fib 11 = 89
fib 12 = 144
fib 13 = 233
fib 14 = 377
fib 15 = 610
fib 16 = 987
fib 17 = 1597
fib 18 = 2584
fib 19 = 4181
fib 20 = 6765
fib 21 = 10946
fib 22 = 17711
fib 23 = 28657
fib 24 = 46368
fib 25 = 75025
fib 26 = 121393
fib 27 = 196418
fib 28 = 317811
fib 29 = 514229
fib 30 = 832040
fib 31 = 1346269
fib 32 = 2178309
fib 33 = 3524578
fib 34 = 5702887
fib 35 = 9227465
fib 36 = 14930352
fib 37 = 24157817
fib 38 = 39088169
fib 39 = 63245986
fib 40 = 102334155
fib 41 = 165580141
fib 42 = 267914296
fib 43 = 433494437
fib 44 = 701408733
fib 45 = 1134903170
root@freescale /mnt/nfs$ ./mt-example 
Multithread test succeeded!
root@freescale /mnt/nfs$ ./mt-example 
Multithread test succeeded!
root@freescale /mnt/nfs$ 
root@freescale /mnt/nfs$ 
root@freescale /mnt/nfs$ ./testsuite 
hello
world!
hello 2
world! 2
Test suite succeeded!
```

except benchmark:
```
benchmark.c: In function ‘bench_switch’:
benchmark.c:34:20: warning: implicit declaration of function ‘rdtsc’ [-Wimplicit-function-declaration]
   34 |   uint64_t start = rdtsc();
      |                    ^~~~~
```

**Comment by edubart** [comment]
Nice, so things seems to be working fine there.

> except benchmark:

That's expected, the benchmark was made only for x86, it uses a x86 assembly instruction to measure CPU cycles.

**Comment by liigo** [comment]
closing
