### ISSUE TITLE
Metal context creation + cmake support

### ISSUE THREAD

**Issue by likun123687** [RandyGaul/cute_framework#87]
https://github.com/RandyGaul/cute_framework/blob/043c2c298eb08a99458befac5132311c7e47125a/include/cute_app.h#L41-L51

**Comment by RandyGaul** [comment]
Hi there, metal is absolutely planned for v1.00 of CF! The graphics API in CF is implemented with sokol_gfx.h (https://github.com/floooh/sokol). Thanks to this cool library we can use:
- GL Core 3.3
- GLES2
- GLES3
- D3D11
- Metal
- WebGPU

For CF there's a couple todo items in order to hook up Metal properly.
- Modify cmake scripts and add in proper defines to setup sokol_gfx.h with metal
- Create the metal context (much like there's custom code in CF to [create a D3D11 context](https://github.com/RandyGaul/cute_framework/blob/master/src/internal/cute_dx11.cpp))

I'll hijack your issue here and add it to the v.100 milestone as a todo item.

**Comment by likun123687** [comment]
Cool, thanks your great work.

**Comment by RandyGaul** [comment]
Looks like there's some support from SDL2 on Metal I didn't even know existed
https://wiki.libsdl.org/SDL2/SDL_CreateWindow
https://wiki.libsdl.org/SDL2/SDL_Metal_CreateView

**Comment by RandyGaul** [comment]
https://github.com/RandyGaul/cute_framework/commit/9176eb39a01eb053233196db9e1980977e5e5ff7
